remote_theme: zendesk/jekyll-theme-zendesk-garden@main
title: Eales Lab Webpage
description: Webpage for the Eales Lab at the University of Manchester
google_analytics: [G-5WS2QG178X]

sidebar:
  - index
  - people
  - publications
  - presentations-and-posters
